server:
  port: 8082
spring:
  application:
    name: demo-book-service
eureka:
  client:
    service-url:
      defaultZone: http://gaoyang:875925@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5