server:
  port: 8081
spring:
  application:
    name: demo-eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://gaoyang:875925@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}