server:
  port: 8761

spring:
  security:
    user:
      name: gaoyang
      password: 875925
  application:
    name: demo-eureka

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    #由于该应用为注册中心，所以设置为false，代表不向主从中心注册自己
    register-with-eureka: false
    #由于注册中心的职责是维护服务实例，它并不需要检索服务，所以设置为false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
